### ISSUE TITLE
Support for MapBox v3 (WebGL2)

### ISSUE THREAD

**Issue by nickginsberg** [vinayakkulkarni/mapbox-gl-interpolate-heatmap#1131]
Hi team,

Hoping to get some insight into what changes might be required for Mapbox v3 support. When using v2 or v3, it seems that WebGL2 is used and does not have support for the WebGL1 features required, and the below exception is thrown (per layer.ts):

```
    if (
      !gl.getExtension('OES_texture_float') ||
      !gl.getExtension('WEBGL_color_buffer_float') ||
      !gl.getExtension('EXT_float_blend')
    ) {
      throw 'WebGL extension not supported';
    }
```

Looking further into it, EXT_float_blend is available, but OES_texture_float and WEBGL_color_buffer_float are not. From the docs (https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_color_buffer_float), seems these are not available in WebGL2 contexts.

I'm not a WebGL expert so I'm not sure specifically what needs to be updated, but thought it would be worth reporting.

**Comment by Rylern** [comment]
I added support for Mapbox v3 on the [original version of the library](https://github.com/Rylern/InterpolateHeatmapLayer).

**Comment by nickginsberg** [comment]
Oh awesome, didn't realize that! Thanks for the info!

**Comment by nfour** [comment]
This would be a great addition as the deck.gl etc. are moving to v3 now.
