### ISSUE TITLE
Bugged colors when using multiple layers

### ISSUE THREAD

**Issue by andrewfergelbotlink** [vinayakkulkarni/mapbox-gl-interpolate-heatmap#1216]
The heatmap layer seems to calculate colors incorrectly when it's placed on top of another layer and has an opacity level <1. In the attached image, the bug tends to show up where the colors in the background layer are brighter. After some investigating, the bug seems to be coming from line 420 in `src/layer.ts`:

`gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);`

Changing `gl.ONE_MINUS_SRC_ALPHA` to `gl.ONE` seemed to fix the problem, though I haven't extensively tested this change under different circumstances.

![image](https://github.com/vinayakkulkarni/mapbox-gl-interpolate-heatmap/assets/135249237/e188ae2d-7c30-4e54-8e27-8ac9840fb9cd)

**Comment by ranelink** [comment]
Comment to bring issue active.
