### ISSUE TITLE
Compatibility with MapLibre

### ISSUE THREAD

**Issue by andreschardong** [vinayakkulkarni/mapbox-gl-interpolate-heatmap#563]
This is an awesome tool! How difficult would it be to get it working or MapLibre ? I would offer to help, however my knowledge of the MapLibre lib is limited to beginner level.

**Comment by andreschardong** [comment]
Never mind. got it working, just had to tweak a bit the `render` and `prerender` signatures. Awesome work you've done! thanks!

**Comment by shahkashani** [comment]
@andreschardong Any chance you'd be willing to share your code for the workaround?
